name: Deploy to AWS Lambda

on:
  push:
    branches: ['main']

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '22.x'

      - name: install
        run: npm ci

      - name: build
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ap-northeast-1

      - name: Deploy Lambda Function
        uses: aws-actions/aws-lambda-deploy@v1
        with:
          function-name: lambda-deploy-action
          code-artifacts-dir: dist
          handler: index.handler
          runtime: nodejs22.x
          architectures: arm64
          role: ${{ secrets.AWS_LAMBDA_EXECUTION_ROLE_ARN }}
